services:
  db:
    image: mongo:latest
    container_name: rosonatt_db_trabalho  
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    image: rosonatt_trabalho            
    container_name: rosonatt_p1_trabalho 
    ports:
      - "8000:8000"
    environment:
     
      - MONGO_URL=mongodb://db:27017 
    depends_on:
      - db
volumes:
  mongo_data: